# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-02 12:13
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('gtin', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('display_name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('cooking_time', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('recalled', models.BooleanField(default=False)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
    ]
