# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20161202_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinformation',
            name='recalled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
