# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-02 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconsumption',
            old_name='date_time',
            new_name='consumption_datetime',
        ),
    ]
